### ISSUE TITLE
Access of data not possible / server down?

### ISSUE THREAD

**Issue by LarsTeh** [prouff/ASCAD_data#1]
Hi,

I just happened to try to download the ASCAD data, but encountered the error that "the server was not found". The problem persists for different browsers and networksettings (direct acces / VPN).

Could you have a look at the server side whether there is something wrong? I would really appreciate accessing the data.

Thanks a lot!
Lars

**Comment by rben-dev** [comment]
Hi LarsTeh,

Please note that the database has been migrated to https://www.data.gouv.fr/s/resources/ascad/20180530-163000/ASCAD_data.zip since a few months now (the README.md has been updated accordingly). The old server is not up anymore.
Can you try the new link and tell us if this is OK for you?

Regards,

**Comment by LarsTeh** [comment]
Hi Ryad,

thank you for the quick reply.

In the public repo I still see the link to http://data.ascad-databases.ovh/ASCAD_data.zip. Maybe you did not push?! I had a look at the [ASCAD](https://github.com/ANSSI-FR/ASCAD) repo and there the link is adapted in the code - though the in the link in ["Raw data files hashes" section](https://github.com/ANSSI-FR/ASCAD#raw-data-files-hashes) also is the old one. Maybe you can consider to change it there, too.

Thanks again!
Lars

**Comment by rben-dev** [comment]
LarsTeh,

Thanks for the pull request, and you are right : the updates have only been pushed to the main ASCAD repo : https://github.com/ANSSI-FR/ASCAD
Please consider using this main repo as the futur "official" one where updates are pushed :-)
Thanks again for reporting the issues!

Regards,

**Comment by LarsTeh** [comment]
Thank you, that is good to know. I just knew this one existed and was lazy searching for what I wanted in the other one. ;) Appreciate your help very much!

**Comment by rben-dev** [comment]
No problem!

Regards,
